### ISSUE TITLE
Question: best practice for providing data in the repository?

### ISSUE THREAD

**Issue by vsoch** [snakemake-workflows/docs#13]
I'm putting together my first dummy pipeline, and I have toy data that is small enough to store alongside the workflow. Where is the "best practices" spot to put it? I've been looking around the examples but it seems like most don't provide data, or download from a remote. Thank you!

**Comment by vsoch** [comment]
I found that this [repo](https://github.com/snakemake-workflows/ngs-test-data) has "reads" so is there no established best practice (and I could make a data folder, for example?)

**Comment by johanneskoester** [comment]
So, all the repos here have a folder .test/data which is a git submodule that points to snakemake-workflows/ngs-test-data. CI testing is conducted in that folder. I would suggest to follow a similar strategy. Create a separate repo with your test data, and integrate it like described above into your workflow repo. Then run the workflow with the .test folder as working directory from e.g. travis CI. See here: https://github.com/snakemake-workflows/rna-seq-star-deseq2/blob/master/.travis.yml#L28

**Comment by johanneskoester** [comment]
You can of course also mention the test data in the readme, so that people can try it out themselves, similar to how travis is configured.

**Comment by vsoch** [comment]
Gotcha! Is this the expected strategy specifically for test data? What about the actual pipeline data (that you instruct the user to add / use via samples.csv. So far I've seen folders for reads, ref, and resources. If it's the case that there isn't a specification, I can consistently organize under a data folder, something like:

```
├── data
│   ├── trimmed/   # output trimmed results
│   ├── reads/       # input reads
│   └── plots/       # output plots
```

Otherwise, if the test data folder is intended to store test and actual data for the pipeline, I can follow suit.

**Comment by johanneskoester** [comment]
The strategy I mentioned is only for test data. Where input data for real applications is stored should usually be up to the user. That is why the user has to define samples.tsv and e.g. the path to the reference genome in the config.yaml. The pipeline should not expect a specific structure.
For results generated by the pipeline itself, they are usually stored directly in the working directory, with subdir per major step, e.g. trimmed, called, plots, tables etc.

**Comment by vsoch** [comment]
okay I'll give that a shot! I'm thinking down the line of trying another go at using the scientific filesystem (modular, predictable organization for containers) [example](https://github.com/sci-f/snakemake.scif) so that there is consistent organization of output between pipelines, at least when containers are involved and we need to bind things. For these early ones (and as I'm re-learning Snakemake) I'll stick to what I'm seeing in the other snakemake-workflows.

Thanks for the speedy reply! Closing issue.
