### ISSUE TITLE
Question: Don't delete temporary wrapper scripts

### ISSUE THREAD

**Issue by vsoch** [snakemake-workflows/docs#15]
I'm trying to get Snakemake working with Singularity, and I need to debug the Singularity command, but the script wrapper that does the execution doesn't exist after the failure, e.g., I need to test:

```bash
 singularity exec --home /home/vanessa/Documents/Dropbox/Code/labs/cherry/snakemake/encode-demo-workflow  --bind /home/vanessa/anaconda3/lib/python3.7/site-packages:/mnt/snakemake /home/vanessa/Documents/Dropbox/Code/labs/cherry/snakemake/encode-demo-workflow/.snakemake/singularity/328e6123b3d8f239ce917fa97ccbbd80.simg bash -c 'set -euo pipefail;  python /home/vanessa/Documents/Dropbox/Code/labs/cherry/snakemake/encode-demo-workflow/.snakemake/scripts/tmp2navashs.wrapper.py'
```
And why is home being force bound to be the present working directory? That seems strange for Singularity. Should it be `--pwd`?

**Comment by johanneskoester** [comment]
@vsoch may I ask you to move this issue to github.com/snakemake/snakemake? This repo is only for the best practice workflows. I will create an issue template which makes this more clear.
