### ISSUE TITLE
I am working on a ChIP-Seq pipeline in Snakemake

### ISSUE THREAD

**Issue by endrebak** [snakemake-workflows/docs#3]
We are hoping to publish it as an applications note. Work in progress here:

https://github.com/biocore-ntnu/chip_seq_pipeline

Just a heads-up. 

It is massive so reviewing it will probably be hard :/ Any feedback appreciated though :) Going to focus hard on finishing the docs and getting a beta out.

Edit: I see that I do not have an integration test, just plenty of dryrun tests testing the DAG logic. I started this before learning about this repo, so I might not be following best practices :/

**Comment by johanneskoester** [comment]
Great! I have only quickly scrolled through it so far. A first comment: it would be great if you could use [wrappers](https://snakemake-wrappers.readthedocs.io) for all tools like hisat2, epic and so on. This way, others can easily compose new workflows from these, and your code also becomes shorter. Finally, wrappers can be unit-tested.

**Comment by johanneskoester** [comment]
@endrebak what is the status of your chip-seq pipeline? Are you still planning to finalize it and include it into snakemake-workflows?

**Comment by endrebak** [comment]
Sorry, no. Have not worked on it for a while. It seemed hard to publish, so I focused on other stuff. Sorry for leaving this open. If sb. wants to create a new ChIP-Seq pipeline, I am available for discussions/PRs.
