### ISSUE TITLE
Accel Amplicon trimming workflow

### ISSUE THREAD

**Issue by Smeds** [snakemake-workflows/docs#4]
I have created a repository, with a Snakemake workflow, used to  trim data generated using [Accel Amplicon Panel](https://swiftbiosci.com/applications/amplicon-sequencing/) data using the recommended guidelines provided by [Swift Biosciences](https://swiftbiosci.com/)

https://github.com/clinical-genomics-uppsala/accel_amplicon_trimming

**Comment by johanneskoester** [comment]
Very nice! Thank you! I have a couple of comments:

* First, thinking about the sample handling, I think it would be better to not assume a fixed pattern of naming. This might differ a lot between sequencing centers. Instead, it would be better to handle samples as you can see in the rna-seq-star-deseq2 repository, where complete filepaths are given in the sample sheet.
* The two trimmomatic rules can most likely be merged into one when using above approach. You simply look up the fastq file in the sample sheet.
* The introductory docstring is duplicated in the two snakefiles.
* What is the purpose of the two different merge rules at the end? Can this be simplified?
* In general, it would be better to put data into subfolders. This way, your workdir is not flooded with files.

**Comment by Smeds** [comment]
Thanks for the response!

I have made some changes to the code https://github.com/clinical-genomics-uppsala/accel_amplicon_trimming/pull/3

I have a question about samples with multiple fastq files, for example from multiple lanes. Should one merge the fastq files before running the workflow? Using the sample file in rna-seq-star-desec-2 repository makes it hard config multiple pairs of fastq files for one sample. 

I know that most of the documentation in the Snakefile and the accel_amplicon.smk file overlap, thought it could be good for people who would like to use the rule directly without looking at the Snakefile. I can remove it from the accel_amplicon.smk file.

**Comment by johanneskoester** [comment]
Handling of samples and technical replicates (e.g., lanes) is indeed an important question. Right now, the deseq2-pipeline does not implement that. One possibility is to add another column `replicate` (which could be the lane) to the sample sheet. However, once people add more columns specific to the biological sample, things become complicated. Another possibility is to have a separate sheet for sequencing units, that simply connects samples to sequencing units (e.g. lanes, technical replicates), allowing multiple lines per sample. We would have a samples.tsv, containing only sample specific information, and a units.tsv, containing the columns `sample, unit, fq1, fq2`. Then, the unit column can hold the lane, while the sample column connects to the sample sheet. Together, sample and unit have to be unique.

I think removing the initial documentation from the code files and moving the stuff into the readme is most appropriate.

**Comment by johanneskoester** [comment]
I think I prefer the second possibility. I will see if I have time to modify the deseq2 pipeline in this way today.

**Comment by Smeds** [comment]
I also like the second option, it should keep everything a bit cleaner. I will try to implement in my workflow tomorrow.

**Comment by johanneskoester** [comment]
Ok, I am finished with the changes for the deseq2 pipeline. Please see snakemake-workflows/rna-seq-star-deseq2#2. Reading the two sheets is a three-liner with pandas, but if this becomes standard, we will have a python package or a module to include.

**Comment by Smeds** [comment]
I have implemented the option of specifying units for samples now.

**Comment by johanneskoester** [comment]
Since this is now included, closing.
